import {StudyExplanation} from './StudyExplanation';
import {useEffect,useState} from 'react';
import {Home,BookOpen,RotateCcw,BarChart3,ShieldCheck,Star,ChevronLeft,ChevronRight} from 'lucide-react';
type Card={id:string;year:number;round:string;subject:string;numbers:string;title:string;body:string};
type RecordEntry={known?:boolean;star?:boolean;uncertain?:boolean};
const key='industrial-safety-study-v1';
function Rich({text}:{text:string}){return <>{text.split(/(\*\*.*?\*\*)/g).map((s,i)=>s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s)}</>}
export function App(){
 const [cards,setCards]=useState<Card[]>([]),[error,setError]=useState(''),[tab,setTab]=useState('home');
 const [records,setRecords]=useState<Record<string,RecordEntry>>(()=>{try{const v=JSON.parse(localStorage.getItem(key)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch{return {}}});
 const [storageError,setStorageError]=useState(false),[year,setYear]=useState('전체'),[round,setRound]=useState('전체'),[subject,setSubject]=useState('전체'),[search,setSearch]=useState(''),[review,setReview]=useState('again');
 const [session,setSession]=useState<Card[]>([]),[index,setIndex]=useState(0),[revealed,setRevealed]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/cards.json`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setCards).catch(()=>setError('학습 자료를 불러오지 못했습니다. 새로고침해 주세요.'))},[]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(records));setStorageError(false)}catch{setStorageError(true)}},[records]);
 const record=(id:string)=>records[id]||{};
 const learned=cards.filter(c=>typeof record(c.id).known==='boolean').length;
 const known=cards.filter(c=>record(c.id).known===true).length;
 const again=cards.filter(c=>record(c.id).known===false);
 const filtered=cards.filter(c=>(year==='전체'||String(c.year)===year)&&(round==='전체'||c.round===round)&&(subject==='전체'||c.subject===subject)&&(!search||`${c.title} ${c.body}`.includes(search)));
 const reviewing=cards.filter(c=>review==='again'?record(c.id).known===false:review==='star'?record(c.id).star:record(c.id).uncertain);
 const current=session[index];
 function update(id:string,value:RecordEntry){setRecords(prev=>({...prev,[id]:{...prev[id],...value}}))}
 function resetRating(id:string){setRecords(prev=>{const next={...prev};const value={...next[id]};delete value.known;next[id]=value;return next})}
 function start(items:Card[]){if(!items.length)return;setSession(items);setIndex(0);setRevealed(false);setDone(false);setTab('study')}
 function move(n:number){setIndex(n);setRevealed(false)}
 const subjects=[...new Set(cards.map(c=>c.subject))];
 return <div className="shell"><header><div className="brand"><ShieldCheck/><div><small>2020—2025 기출 학습</small><h1>산업안전기사</h1></div></div><span className="badge">필기</span></header>
 {storageError&&<p role="alert" className="notice">저장 공간에 접근할 수 없어 이번 학습 기록은 새로고침하면 사라질 수 있습니다.</p>}
 {error?<p role="alert">{error}</p>:!cards.length?<p>학습 자료를 불러오는 중…</p>:<main>
 {tab==='home'&&<><section className="hero"><span>하루 한 걸음, 합격에 더 가까이</span><h2>오늘도 안전하게,<br/>실력을 쌓아보세요.</h2><p>17개 회차의 핵심 내용을 한곳에서 학습하세요.</p><button className="light" onClick={()=>start(cards.filter(c=>record(c.id).known!==true).slice(0,20))}>오늘의 20개 학습 <ChevronRight size={18}/></button></section><div className="metrics"><article><small>전체 학습 카드</small><b>{cards.length.toLocaleString()}</b></article><article><small>학습한 카드</small><b>{learned.toLocaleString()}</b></article><article><small>알아요</small><b>{known.toLocaleString()}</b></article></div><section className="panel"><h3>나의 학습 진행률 <span>{Math.round(learned/cards.length*100)}%</span></h3><progress value={learned} max={cards.length}/><p>해설을 확인하고 이해도를 기록해 보세요.</p></section><h3>빠른 학습</h3><div className="quick"><button onClick={()=>setTab('exams')}><BookOpen/>회차별 기출 학습<ChevronRight/></button><button onClick={()=>{setReview('again');setTab('review')}}><RotateCcw/>다시 학습할 카드 <b>{again.length}</b></button></div><p className="notice">제공된 MD를 학습 카드로 구성했습니다. 객관식 보기 없이 핵심 주제와 해설을 확인하고 스스로 평가합니다. 2022년 3회차 이후 자료는 복원본 기반이며, 법령·수치는 제공 자료의 내용을 그대로 표시합니다.</p></>}
 {tab==='exams'&&<><h2>기출 학습</h2><p className="subtitle">연도와 회차를 골라 차근차근 학습하세요.</p><section className="panel filters"><label>연도<select value={year} onChange={e=>{setYear(e.target.value);setRound('전체')}}>{['전체',...new Set(cards.map(c=>String(c.year)))].map(v=><option key={v}>{v}</option>)}</select></label><label>회차<select value={round} onChange={e=>setRound(e.target.value)}>{['전체',...new Set(cards.filter(c=>year==='전체'||String(c.year)===year).map(c=>c.round))].map(v=><option key={v} value={v}>{v==='전체'?v:`${v}회차`}</option>)}</select></label><label className="wide">과목<select value={subject} onChange={e=>setSubject(e.target.value)}>{['전체',...subjects].map(v=><option key={v}>{v}</option>)}</select></label><label className="wide">내용 검색<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="예: 안전관리, 감전, 비계"/></label></section><button className="primary full" disabled={!filtered.length} onClick={()=>start(filtered)}>{filtered.length.toLocaleString()}개 카드 학습 시작</button><CardList items={filtered}/></>}
 {tab==='review'&&<><h2>복습</h2><p className="subtitle">한 번 더 보면, 더 오래 기억할 수 있어요.</p><div className="segments">{[['again','다시 학습'],['uncertain','아리까리'],['star','즐겨찾기']].map(([v,label])=><button className={review===v?'active':''} key={v} onClick={()=>setReview(v)}>{label}</button>)}</div><button className="primary full" disabled={!reviewing.length} onClick={()=>start(reviewing)}>{reviewing.length}개 카드 복습 시작</button><CardList items={reviewing}/></>}
 {tab==='stats'&&<><h2>학습 통계</h2><p className="subtitle">‘알아요’ 비율은 직접 기록한 이해도입니다.</p><section className="panel"><h3>학습한 카드 중 알아요</h3><b className="large">{learned?Math.round(known/learned*100):0}%</b><p>학습 {learned}개 · 알아요 {known}개 · 다시 학습 {again.length}개</p></section><h3>과목별 학습 현황</h3>{subjects.map(s=>{const all=cards.filter(c=>c.subject===s),count=all.filter(c=>typeof record(c.id).known==='boolean').length;return <section key={s} className="panel"><h3>{s}</h3><progress value={count} max={all.length}/><p>{count} / {all.length}개 학습</p></section>})}</>}
 {tab==='study'&&current&&!done&&<><button className="back" onClick={()=>setTab('exams')}><ChevronLeft size={18}/> 기출 목록</button><div className="studyhead"><span>{current.year}년 {current.round}회차</span><span>{index+1} / {session.length}</span></div><progress value={index+1} max={session.length}/><section className="panel question"><small>{current.subject} · {current.numbers}번</small><h2><Rich text={current.title}/></h2><div className="tools"><button className={record(current.id).star?'selected':''} aria-pressed={!!record(current.id).star} onClick={()=>update(current.id,{star:!record(current.id).star})}><Star size={17}/>즐겨찾기</button><button className={record(current.id).uncertain?'selected':''} aria-pressed={!!record(current.id).uncertain} onClick={()=>update(current.id,{uncertain:!record(current.id).uncertain})}>? 아리까리</button></div>{typeof record(current.id).known==='boolean'&&<button className="reset-rating" onClick={()=>resetRating(current.id)}>학습 평가 취소</button>}{!revealed?<div className="reveal"><p>핵심 내용을 먼저 떠올려 보세요.</p><button className="primary" onClick={()=>setRevealed(true)}>해설 확인</button></div>:<><StudyExplanation title={current.title} body={current.body}/><p className="subtitle">이 내용을 얼마나 알고 있나요?</p><div className="ratings"><button className={record(current.id).known===false?'selected':''} onClick={()=>update(current.id,{known:false})}>다시 학습</button><button className={record(current.id).known===true?'selected':''} onClick={()=>update(current.id,{known:true})}>✓ 알아요</button></div></>}</section><div className="paging"><button disabled={index===0} onClick={()=>move(index-1)}>이전</button><button className="primary" onClick={()=>index===session.length-1?setDone(true):move(index+1)}>{index===session.length-1?'학습 마치기':'다음'}<ChevronRight size={18}/></button></div></>}
 {tab==='study'&&done&&<section className="panel finish"><ShieldCheck size={48}/><h2>이번 학습을 마쳤어요</h2><p>{session.length}개 중 {session.filter(c=>typeof record(c.id).known==='boolean').length}개 이해도 기록</p><button className="primary" onClick={()=>setTab('home')}>홈으로</button><button onClick={()=>start(session.filter(c=>record(c.id).known===false))} disabled={!session.some(c=>record(c.id).known===false)}>다시 학습할 카드 복습</button></section>}
 </main>}<nav>{[['home','홈',Home],['exams','기출',BookOpen],['review','복습',RotateCcw],['stats','통계',BarChart3]].map(([id,label,Icon])=>{const I=Icon as typeof Home;return <button key={id as string} className={tab===id?'active':''} onClick={()=>setTab(id as string)}><I size={22}/>{label as string}</button>})}</nav><footer>학습 기록은 이 브라우저에 저장됩니다.</footer></div>;
 function CardList({items}:{items:Card[]}){const [page,setPage]=useState(0);const pageSize=30;const startAt=page*pageSize;return <div className="list">{!items.length?<section className="panel">해당하는 카드가 없습니다.</section>:<><p className="subtitle">{items.length}개 결과 · {startAt+1}–{Math.min(startAt+pageSize,items.length)}</p>{items.slice(startAt,startAt+pageSize).map(c=><button key={c.id} onClick={()=>start(items.slice(items.indexOf(c)))}><small>{c.year}년 {c.round}회차 · {c.numbers}번</small><span><Rich text={c.title}/></span><small>{c.subject}{record(c.id).known===true?' · ✓ 알아요':''}</small></button>)}<div className="paging"><button disabled={page===0} onClick={()=>setPage(page-1)}>이전 목록</button><span>{page+1} / {Math.ceil(items.length/pageSize)}</span><button disabled={startAt+pageSize>=items.length} onClick={()=>setPage(page+1)}>다음 목록</button></div></>}</div>}
}
